[package]
name = "learning_rust"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "arrays_vectors"
path = "src/1_arrays_vectors.rs"

[[bin]]
name = "functional_flavored" 
path = "src/2_functional_flavored.rs"
